name: Run JS Programs

on: [push]

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run JS files
        run: |
          for file in JSPractice/*.js
          do
            echo "Running $file"
            node $file
          done